#if os(macOS) && MACCOMPANION_VNC_DEVELOPMENT
// SwiftTerm can synthesize mouse movement from its own local event monitor.
// Recognize its X10/UTF-8, SGR (cell/pixel), and urxvt reports without blocking
// terminal query replies generated by a background connection.
enum MacTerminalMouseReport {
    // SwiftTerm's normal SGR release clears the button bits. Restore the
    // native event's identity before sending or accounting for that release.
    static func correctingSGRRelease(_ bytes: ArraySlice<UInt8>, button: Int?) -> [UInt8]? {
        guard let button, (0...2).contains(button), bytes.last == 109, contains(bytes) else { return nil }
        let prefix: [UInt8], body: ArraySlice<UInt8>
        if bytes.starts(with: [27, 91, 60]) { prefix = [27, 91, 60]; body = bytes.dropFirst(3) }
        else if bytes.starts(with: [155, 60]) { prefix = [155, 60]; body = bytes.dropFirst(2) }
        else { return nil }
        let fields = body.dropLast().split(separator: 59)
        guard let flags = Int(String(decoding: fields[0], as: UTF8.self)), flags & 64 == 0 else { return nil }
        let payload = String((flags & ~32 & ~3) | button) + ";" + String(decoding: fields[1], as: UTF8.self)
            + ";" + String(decoding: fields[2], as: UTF8.self)
        return prefix + Array(payload.utf8) + [109]
    }
    static func contains(_ bytes: ArraySlice<UInt8>) -> Bool {
        let body: ArraySlice<UInt8>
        if bytes.starts(with: [27, 91]) { body = bytes.dropFirst(2) }
        else if bytes.first == 155 { body = bytes.dropFirst() }
        else { return false }
        if body.first == 77 { return body.count >= 4 }
        guard body.last == 77 || body.last == 109 else { return false }
        var fields = body.dropLast()
        if fields.first == 60 { fields = fields.dropFirst() }
        else if body.last != 77 { return false }
        let values = fields.split(separator: 59, omittingEmptySubsequences: false)
        return values.count == 3 && values.allSatisfy { !$0.isEmpty && $0.allSatisfy { (48...57).contains($0) } }
    }
}
#endif
