#if os(macOS) && MACCOMPANION_VNC_DEVELOPMENT
// SwiftTerm can synthesize mouse movement from its own local event monitor.
// Recognize its X10/UTF-8, SGR (cell/pixel), and urxvt reports without blocking
// terminal query replies generated by a background connection.
enum MacTerminalMouseReport {
    static func contains(_ bytes: ArraySlice<UInt8>) -> Bool {
        let body: ArraySlice<UInt8>
        if bytes.starts(with: [27, 91]) { body = bytes.dropFirst(2) }
        else if bytes.first == 155 { body = bytes.dropFirst() }
        else { return false }
        if body.first == 77 { return body.count >= 4 }
        guard body.last == 77 || body.last == 109 else { return false }
        var fields = body.dropLast()
        if fields.first == 60 { fields = fields.dropFirst() }
        else if body.last != 77 { return false }
        let values = fields.split(separator: 59, omittingEmptySubsequences: false)
        return values.count == 3 && values.allSatisfy { !$0.isEmpty && $0.allSatisfy { (48...57).contains($0) } }
    }
}
#endif
